[project]
name = "deep-eval-agent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "mysql-connector-python>=9.4.0",
    "pydantic>=2.11.7",
]
